apiVersion: v1
kind: Service
metadata:
  name: java-palindrome-number-service
spec:
  selector:
    app: java-palindrome-number
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
